### PR TITLE
Embedding Images and Video

### PR DESCRIPTION
**Pull request by Godswilly**
Embedding Images and Video:

In this project we:
-Added a navbar section.
-Embedded a video on the main section.
-Embedded Images on the aside section.
-Added share, subscribe buttons too.
-Added comments at the end.

### CODE REVIEW

**Comment by lucasmazo32** [comment]
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. Kuddos on using the favicon and using gifs for the side videos. Commits are descriptive. It was a really good project to review.

For the project to get approved kindly implement these changes:

## Required changes:

- [ ] Please modify your README file. You can use this [template](https://github.com/microverseinc/readme-template).

- [ ] Change the share and subscribe tags to button, instead of anchor (```<button></button>```).
> Screenshot from your code
image

### Happy coding! :computer:

## Lucas Mazo

**Comment by santiago-dev96** [comment]
## Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
## Changes required :no_good_man:

I can't review this project until it becomes a professional one, your PR doesn't provide a description at all, and your `README.md` file doesn't have a proper title. Please submit another CRR after implementing the changes.

Friendly reminder: You should make sure that your repo looks professional before review. Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there). This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

You can reach me on Slack as **srodrig**

**Review by serdg0 — CHANGES_REQUESTED** [review]
Hello guys,

I have to submit this project as invalid due to lack of a professional README. Feel free to copy this [template](https://github.com/microverseinc/readme-template). Make sure to add the headers, your corresponding links in the authors parts. Double check all what is provided there before submiting for another review, just to be sure.

Feel free to reach me in slack! 

Sergio Diaz Gonzalez

**Comment by Godswilly** [comment]
Okay sir. I hope no issues with the PR.

**Comment by Godswilly** [comment]
I can't find you on slack sir.

**Review by lucasmazo32 — APPROVED** [review]
# Project approved :rocket:

Great job implementing the changes.

My suggestion for future projects is to use microverse template until you find a better one (or create your own) that looks as professional as the one provided.

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

**Pull request merged**
